# yaml-language-server: $schema=https://raw.githubusercontent.com/traefik/traefik-helm-chart/refs/heads/master/traefik/values.schema.json
deployment:
  replicas: 2
  initContainers:
    - name: volume-permissions
      image: busybox:latest
      command:
        - sh
        - -c
        - touch /data/acme.json; chmod -v 600 /data/acme.json
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 65532
      volumeMounts:
        - mountPath: /data
          name: traefik-data
    - name: init-ca
      image: ghcr.io/jhofer-cloud/jhc-ca:latest
      command:
        [
          "/bin/sh",
          "-c",
          "cp /usr/local/share/ca-certificates/custom-ca.crt /etc/ssl/certs/custom-ca.crt && update-ca-certificates",
        ]
      volumeMounts:
        - name: ssl-certs
          mountPath: /etc/ssl/certs
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        readOnlyRootFilesystem: false
        runAsNonRoot: true
        runAsUser: 65532
  additionalVolumes:
    - name: ssl-certs
      emptyDir: {}
  additionalVolumeMounts:
    - name: ssl-certs
      mountPath: /etc/ssl/certs
      readOnly: false
podSecurityContext:
  fsGroup: 65532
  fsGroupChangePolicy: "OnRootMismatch"
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  readOnlyRootFilesystem: true

ingressRoute:
  dashboard:
    enabled: true
    annotations: {}
    labels: {}
    # MatchRule gets set in helm-ci for traefik
    entryPoints:
      - websecure
    middlewares: []
    tls:
      certResolver: labca
    services:
      - name: api@internal
        kind: TraefikService

dashboard:
  enabled: true

experimental:
  plugins: {}

ports:
  web:
    port: 80
    expose:
      default: true
    exposedPort: 80
    protocol: TCP
  websecure:
    port: 443
    expose:
      default: true
    exposedPort: 443
    protocol: TCP
    tls:
      enabled: true

service:
  type: LoadBalancer
  spec:
    externalIPs:
      ##TODO: Add mode control/worker nodes
      - "10.2.1.214"
      - "10.2.1.161"

persistence:
  enabled: true
  name: traefik-data
  accessMode: ReadWriteMany
  size: 128Mi
  path: /data
  storageClass: longhorn

certificatesResolvers:
  labca:
    acme:
      email: admin@jhofer.de
      caServer: "https://pki.jhofer.lan/directory"
      storage: /data/acme.json
      httpChallenge:
        entryPoint: web

additionalArguments:
  - --api=true
  - --api.insecure=true
  - --api.dashboard=true
  - --providers.kubernetesIngress=true
  - --providers.kubernetesCRD=true
  - --serverstransport.insecureskipverify=false
  - --log.level=INFO
  - --entrypoints.web.http.redirections.entryPoint.to=websecure
  - --entrypoints.web.http.redirections.entryPoint.scheme=https
  - --serversTransport.rootCAs=/etc/ssl/certs/ca-certificates.crt
