deployment:
  kind: DaemonSet

additionalArguments:
  - --api.dashboard=true
  - --api.insecure=true ##FIX: Disable insecure later
  - --serverstransport.insecureskipverify=true
  - --log.level=INFO

ports:
  web:
    port: 80
    expose:
      default: true
    exposedPort: 80
    protocol: TCP
  websecure:
    port: 443
    expose:
      default: true
    exposedPort: 443
    protocol: TCP

service:
  type: LoadBalancer
  spec:
    externalTrafficPolicy: Local

ingressRoute:
  dashboard:
    enabled: true
    annotations: {}
    entryPoints: ["web", "websecure"]

rbac:
  enabled: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

securityContext:
  capabilities:
    drop: [ALL]
    add: [NET_BIND_SERVICE]
  readOnlyRootFilesystem: true
  runAsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532

podSecurityContext:
  fsGroup: 65532
