deployment:
  kind: Deployment
  replicas: 1
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - traefik
          topologyKey: "kubernetes.io/hostname"

ingressRoute:
  dashboard:
    enabled: true
    annotations: {}
    labels: {}
    # MatchRule gets set in helm-ci for traefik
    entryPoints:
      - websecure
    middlewares: []
    tls: {}
    # tls:
    #   certResolver: labca
    services:
      - name: api@internal
        kind: TraefikService

dashboard:
  enabled: true

experimental:
  plugins: {}

ports:
  web:
    port: 80
    expose:
      default: true
    exposedPort: 80
    protocol: TCP
  websecure:
    port: 443
    expose:
      default: true
    exposedPort: 443
    protocol: TCP
    tls:
      enabled: true

service:
  type: LoadBalancer
  spec:
    externalIPs:
      - "10.2.1.214"
      - "10.2.1.161"

additionalArguments:
  - --api=true
  - --api.insecure=true
  - --api.dashboard=true
  - --providers.kubernetesIngress=true
  - --providers.kubernetesCRD=true
  - --serverstransport.insecureskipverify=true
  - --log.level=INFO
  - --entrypoints.web.http.redirections.entryPoint.to=websecure
  - --entrypoints.web.http.redirections.entryPoint.scheme=https

# certificatesResolvers:
#   labca:
#     acme:
#       email: admin@jhofer.de
#       caServer: "https://pki.jhofer.lan/directory"
#       storage: /data/acme.json
#       httpChallenge:
#         entryPoint: web

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

logs:
  level: INFO
