name: Deploy Traefik
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev
jobs:
  traefik:
    uses: JHOFER-Cloud/helm-ci/.github/workflows/k8s-deploy-template.yml@dev
    with:
      app_name: traefik
      helm_repository: https://traefik.github.io/charts
      helm_chart: traefik/traefik
      helm_version: 33.2.1
      values_path: helm/values
      ##TODO:
      # external_domain: jhofer.org ## As example; If not set fallback to internal_domain
      # external_acme: true ## Letsencrypt; false or not set = internal_acme
      # external_acme_email: admin@jhofer.de
      # internal_acme: https://pki.jhofer.lan/directory
      internal_domain: k8.hla1.jhofer.lan ## CUSTOM ACME
      traefik_dashboard: true
      root_ca: "https://pki.jhofer.lan/certs/root-ca.pem"
    secrets:
      KUBE_CONFIG_DEV: ${{ secrets.KUBE_CONFIG_DEV }} ## HLA1 CONFIG
      KUBE_CONFIG_LIVE: ${{ secrets.KUBE_CONFIG_LIVE }} ## EMPTY CONFIG
