name: Deploy Traefik

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    uses: JHOFER-Cloud/helm-ci/.github/workflows/k8s-deploy-template.yml@main
    with:
      app_name: traefik
      helm_repository: https://traefik.github.io/charts
      helm_chart: traefik/traefik
      helm_version: 24.0.0
      values_path: helm/values
      ingress_domain: jhofer.lan
    secrets:
      KUBE_CONFIG_DEV: ${{ secrets.KUBE_CONFIG_DEV }}
      KUBE_CONFIG_LIVE: ${{ secrets.KUBE_CONFIG_LIVE }}
